name: Publish Module

on:
  workflow_run:
    workflows: [LinuxProd]
    types:
      - completed
jobs:
  PublishToPSGallery:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Runs a set of commands using the runners shell
      - name: Setup Environment
        shell: pwsh
        run: ./build.ps1 "ImportModules"
      
      - name: Publish
        shell: pwsh
        run: ./build.ps1 "PublishModule" -NugetAPIKey "${{ secrets.NUGET_API_KEY }}"
